name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login into Github Docker Registery
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build the Docker image
      run: docker build -t ghcr.io/shyim/devcontainers-php:8.1-fpm ./8.1-fpm
      
    - name: Push the image
      run: docker push ghcr.io/shyim/devcontainers-php:8.1-fpm
